version: '3.8'

services:
  # MCP Servers
  input:
    build: ./mcp-servers/input
    container_name: reel-factory-input
    environment:
      - MCP_SERVER_NAME=input-processor
    ports:
      - "8081:8080"
    networks:
      - rocket-reels-network
    volumes:
      - ./outputs:/app/outputs

  research:
    build: ./mcp-servers/research
    container_name: reel-factory-research
    environment:
      - MCP_SERVER_NAME=research
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8082:8080"
    networks:
      - rocket-reels-network

  planner:
    build: ./mcp-servers/planner
    container_name: reel-factory-planner
    environment:
      - MCP_SERVER_NAME=content-planner
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8083:8080"
    networks:
      - rocket-reels-network

  script:
    build: ./mcp-servers/script
    container_name: reel-factory-script
    environment:
      - MCP_SERVER_NAME=script-writer
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "8084:8080"
    networks:
      - rocket-reels-network

  visual:
    build: ./mcp-servers/visual
    container_name: reel-factory-visual
    environment:
      - MCP_SERVER_NAME=visual-generator
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    ports:
      - "8085:8080"
    networks:
      - rocket-reels-network
    volumes:
      - ./outputs:/app/outputs
      - ./credentials:/app/credentials:ro

  # Orchestrator with Human Review Interface
  orchestrator:
    build: ./orchestrator
    container_name: reel-factory-orchestrator
    depends_on:
      - input
      - research
      - planner
      - script
      - visual
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=ai-reel-factory
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - COST_LIMIT_PER_REEL=${COST_LIMIT_PER_REEL}
      - COST_LIMIT_DAILY=${COST_LIMIT_DAILY}
    ports:
      - "8000:8000"  # Human review interface
      - "8001:8001"  # API endpoints
    networks:
      - rocket-reels-network
    volumes:
      - ./outputs:/app/outputs
      - ./config:/app/config:ro

networks:
  rocket-reels-network:
    driver: bridge

volumes:
  outputs:
    driver: local